name: Build and Deploy App

on:
  push:
    branches: [ "master" ]

concurrency:
  group: deploy-production
  cancel-in-progress: false    

jobs:
  build:

    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - run: npm ci

      - run: npm run lint

      - run: npm run type-check

      - run: npm run build

      - name: Deploy
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-r"
          SOURCE: ".next/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
          SCRIPT_AFTER_REQUIRED: true
          SCRIPT_AFTER: |
            set -e
            cd ${{ secrets.PATH_TO_FRONTEND_REPO }}
            git pull
            # Lock-basiertes npm ci um Race Conditions zu vermeiden
            flock -x -w 300 /tmp/npm-ci.lock npm ci --production
            supervisorctl restart frontend-daemon
